export const photosdata = [{
    id: 1,
    name: 'Magia',
    description: 'Fuegos artificiales en Disney',
    thumbnail:'./../img/fav1_fuegos_artificiales.jpg',
    price: 5437,
},
{id: 2,
    name: 'Paz',
    description: 'Atardecer en Fort Myers',
    thumbnail:'./img/fav2_atardecer.jpg',
    price: 6229,
},
{id: 3,
    name: 'Gran Ciudad',
    description: 'Playa de Miami',
    thumbnail:'./img/fav3_miami.jpg',
    price: 4923,
},
{id: 4,
    name: 'Viejas Costumbres',
    description: 'Soplando un panadero',
    thumbnail:'./img/fav4_contraluz.jpg',
    price: 3199,
},
{id: 5,
    name: 'Coctel',
    description: 'Gin Tonic',
    thumbnail:'./img/fav5_copa.jpg',
    price: 3199,
},
{id: 6,
    name: 'Amor',
    description: 'Capilla de La Cumbrecita',
    thumbnail:'./img/fav6_la_cumbrecita.jpg',
    price: 3499,
},
{id: 7,
    name: 'Amigo',
    description: 'Perro amigo: El Flaco',
    thumbnail:'./img/fav7_el_flaco.jpg',
    price: 7468,
},
{id: 8,
    name: 'Diegol',
    description: 'Niebla a la salida del Bar',
    thumbnail:'./img/fav8_niebla.jpg',
    price: 3488,
},
{id: 9,
    name: 'Libélula',
    description: 'Posada con tranquilidad',
    thumbnail:'./img/fav9_libelula.jpg',
    price: 3488,
},
{id: 10,
    name: 'Azar',
    description: 'Cubilete de Dados',
    thumbnail:'./img/fav10_dados.jpg',
    price: 3717,
},
{id: 11,
    name: 'Dulces placeres',
    description: 'Isla flotante con frutos rojos',
    thumbnail:'./img/fav11_postre.jpg',
    price: 4119,
},
{id: 12,
    name: 'Mi hijo',
    description: 'Rami en la casita de madera',
    thumbnail:'./img/fav12_rami.jpg',
    price: 8719,
},
{id: 13,
    name: 'Retrato',
    description: 'Cubano',
    thumbnail:'./img/fav13_cubano.jpg',
    price: 7339,
},
{id: 14,
    name: 'Mi hija',
    description: 'Martina en el mar',
    thumbnail:'./img/fav14_marti.jpg',
    price: 6111,
},
{id: 15,
    name: 'Hermanos',
    description: 'Hermanos en el mar',
    thumbnail:'./img/fav15_hermanos.jpg',
    price: 6519,
}]


export const usersdata = [
    {   id: 'cmouguelar@gmail.com',
        pass: 'Ramiro' },
    {
        id: 'prueba@gmail.com',
        pass: 'prueba' },
    {
        id: 'coder@gmail.com',
        pass: 'coder'
    }
];